### ISSUE TITLE
Improve Readme

### ISSUE THREAD

**Issue by HridoyHazard** [cdhiraj40/LeetDroid#14]
**Describe the bug**
I would like to increase the readme in a well organized way. kindly assign this task to me

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by cdhiraj40** [comment]
Hey, @HridoyHazard please use the correct issue template. This issue is for the bug report. You should select the feature request template. I will close this one, feel free to create another one with the correct template. Also, add more description to the issue on what you want to change in the readme.
